### ISSUE TITLE
Differentiate dark mode colors

### ISSUE THREAD

**Issue by denver-s** [claudebarde/ConnecTez#1]
Hi, Claude. First of all, great job! It's nice to see Tezos used in the real world.

My issue is that when I switch to dark mode, it's not so easy to distinguish the blog article from the background.

![image](https://user-images.githubusercontent.com/31325316/79484013-5a8ac800-8013-11ea-9de7-9972f64c606c.png)

**Comment by claudebarde** [comment]
Hi!  
Thank you for your feedback :)  
The goal of the dark mode was to make everything dark. Do you mean it would be better to have a black background and a less dark article box?

**Comment by denver-s** [comment]
Yes! Exactly, a darker background and a lighter article box.

**Comment by stocks81** [comment]
I all most thought about what about just a lighter color for the shadow of the article box?

**Comment by claudebarde** [comment]
Something like that? Maybe black on grey is better than grey on black, what do you think?  
  
<img width="1288" alt="Screenshot 2020-04-17 07 59 42" src="https://user-images.githubusercontent.com/25201109/79533860-aaa07380-8081-11ea-8f70-929e7b07014b.png">
<img width="1290" alt="Screenshot 2020-04-17 07 58 56" src="https://user-images.githubusercontent.com/25201109/79533852-a6745600-8081-11ea-8b25-d4be64fa7f80.png">

**Comment by denver-s** [comment]
They’re both nice in my opinion. The first one is probably my favourite, it looks similar to other  apps and websites I use.

**Comment by claudebarde** [comment]
@denver-s Can you give me links of websites with this kind of example so I can have a better idea of how it looks like? Thanks

**Comment by denver-s** [comment]
Reddit (even if it's too dark in my opinion):
![image](https://user-images.githubusercontent.com/31325316/79575315-e0654c80-80c1-11ea-8fe1-58933265b404.png)

CoinCodex:
![image](https://user-images.githubusercontent.com/31325316/79575378-fa9f2a80-80c1-11ea-8f9b-293c65075157.png)

Telegram:
![image](https://user-images.githubusercontent.com/31325316/79575855-b19ba600-80c2-11ea-81b4-c0a6f7926f46.png)

**Comment by claudebarde** [comment]
Thank you for the screenshots!
I've put online a new version with an updated dark mode, it does look better :)
